title: <p align="center"> Azadeh Tofighi </p>

logo: "/images/picture1.png?raw=true"

description:
  <p align="center">
  <a href="https://docs.google.com/document/d/1h0ODSjBtmwJlAEiUWkZh4b6u18Pi4_IS8xpFunYbZ7M/export?format=pdf"> <i class="fa-solid fa-download"></i> Resume </a> |
  <a href="https://www.linkedin.com/in/aztofighi/"><i class="fa-brands fa-linkedin"></i> LinkedIn </a> |
  <a href="https://github.com/aztofighi"><i class="fa-brands fa-github"></i> GitHub </a> <br>
  <a href="https://scholar.google.com/citations?user=1t44pi0AAAAJ&hl=en"><i class="fa-brands fa-square-google-plus"></i> Google Scholar </a> |
  <a href="https://www.researchgate.net/profile/Azadeh-Tofighi-3"><i class="fa-brands fa-researchgate"></i> ResearchGate </a> <br>
  <a href="https://huggingface.co/Azadeh"><i class="fa-solid fa-face-smile-beam"></i> Hugging Face </a> |
  <a href="https://replicate.com/aztofighi"><i class="fa-solid fa-bars"></i> Replicate </a>
  
  </p>
  
  <p align="justify">
  
  Azadeh is a Ph.D. candidate at the University of Tehran, specializing in Artificial Intelligence. Her research interests include Machine Learning, Data Science, Deep Learning, and Computer Vision.
  <br>
  </p>
google_analytics: UA-145578661-1 # Google Analytics tracking ID
