title: <p align="center"> Azadeh Tofighi </p>

logo: "/images/picture1.png?raw=true"

description:
  <p align="center">
  <a href="https://docs.google.com/document/d/1h0ODSjBtmwJlAEiUWkZh4b6u18Pi4_IS8xpFunYbZ7M/export?format=pdf"> <i class="fa-solid fa-download"></i> Resume </a> |
  <a href="https://www.linkedin.com/in/aztofighi/"><i class="fa-brands fa-linkedin"></i> LinkedIn </a> |
  <a href="https://github.com/aztofighi"><i class="fa-brands fa-github"></i> GitHub </a> <br>
  <a href="https://huggingface.co/Azadeh"><i class="fa-solid fa-face-smile-beam"></i> Hugging Face </a> |
  <a href="https://replicate.com/aztofighi"><i class="fa-solid fa-bars"></i> Replicate </a>
  
  </p>
  
  <p align="justify">
  I am pursuing a Ph.D. degree in Artificial Intelligence at the Science Faculty, University of Tehran.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
